### ISSUE TITLE
Upload on MELPA

### ISSUE THREAD

**Issue by AndreaOrru** [wbolster/emacs-python-coverage#3]
Hi! Just wanted to say that I'm using this package and I find it super useful - it's much better and less invasive than some of the other ones on GitHub/MELPA.

Do you have any plans to upload it on MELPA? Anything I can do to help?

**Comment by wbolster** [comment]
i just never got around to it. this was some experimental code but actually it works quite well in practice so maybe it's not that experimental after all.

i may look into this soon. the melpa part is simple, but i'll need to come up with a simple readme first.

**Comment by wbolster** [comment]
now that there's a readme (https://github.com/wbolster/emacs-python-coverage)

i've submitted this to melpa: https://github.com/melpa/melpa/pull/7806
